# Generated by Django 4.2 on 2025-11-29 02:38

from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('default_points', models.IntegerField(default=0)),
                ('is_police', models.BooleanField(default=False)),
                ('is_thief', models.BooleanField(default=False)),
                ('icon', models.CharField(default='default_icon.png', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('avatar', models.CharField(default='default_avatar.png', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('total_score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('is_host', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(default=game.models.generate_room_code, max_length=10, unique=True)),
                ('host_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settings', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('status', models.CharField(choices=[('SHUFFLING', 'Shuffling'), ('REVEAL', 'Reveal'), ('PLAYING', 'Playing'), ('SCORING', 'Scoring'), ('COMPLETED', 'Completed')], default='SHUFFLING', max_length=20)),
                ('winner', models.CharField(blank=True, max_length=20, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('police_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='police_rounds', to='game.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.room')),
                ('thief_player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thief_rounds', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='RoundParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
                ('assigned_points', models.IntegerField(default=0)),
                ('is_caught', models.BooleanField(default=False)),
                ('is_wrongly_accused', models.BooleanField(default=False)),
                ('final_score', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='game.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='game.round')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.room'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('room', 'name')},
        ),
    ]
