# Generated by Django 4.2 on 2025-11-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerole',
            name='default_points',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='room',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='roundparticipation',
            name='assigned_points',
        ),
        migrations.AddField(
            model_name='gamerole',
            name='description',
            field=models.TextField(default='No description available.'),
        ),
        migrations.AddField(
            model_name='gamerole',
            name='lose_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamerole',
            name='win_points',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='room',
            name='max_rounds',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='room',
            name='timer_duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='round',
            name='interrogation_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='round',
            name='remaining_seconds',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='roundparticipation',
            name='lose_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roundparticipation',
            name='role_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='roundparticipation',
            name='win_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('SHUFFLING', 'Shuffling'), ('PLAYING', 'Playing'), ('INTERROGATION', 'Interrogation'), ('COMPLETED', 'Completed')], default='SHUFFLING', max_length=20),
        ),
    ]
